1st pr from dev to main: landing page, navbar, footer, slider, viewing page, DB
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #12
Opened 2024-06-19 14:07 UTC by FabienRollet

2024-06-20 10:58 UTC, FranckWebPro commented on client/.gitignore
style.html written twice

2024-06-20 10:58 UTC, FranckWebPro commented on client/package.json
> +    "fluid-tailwind": "^1.0.0",
fluid tailwind to remove from dependencies

2024-06-20 10:58 UTC, FranckWebPro commented on client/src/components/Footer.jsx
> +            <Link to="/">Pages</Link>
Pages should not be a link

2024-06-20 10:58 UTC, FranckWebPro commented on client/src/components/Footer.jsx
> +            <Link to="/">Catégories</Link>
Catégories should not be a link

2024-06-20 10:58 UTC, FranckWebPro commented on client/src/components/Header.jsx
> +  const [isMenuOpen, setIsMenuOpen] = useState(false);
Add mobile for the variable names

2024-06-20 10:58 UTC, FranckWebPro commented on client/src/components/Header.jsx
> +  const closeMenu = () => {
same

2024-06-20 10:58 UTC, FranckWebPro commented on client/src/components/Navbar.jsx
> +          Menu déroulant
remove "menu deroulant"

2024-06-20 10:58 UTC, FranckWebPro commented on server/app/config.js
remove comment ?

2024-06-20 12:06 UTC, Sylvainlfe approved these changes

2024-06-20 12:06 UTC, Sylvainlfe commented on client/src/components/Header.jsx
> +    uppercase bg-white list-none justify-around items-center transform transition-all duration-300 text-center
uppercase non fonctionnel - uppercase dans button objectif

2024-06-20 12:06 UTC, Sylvainlfe commented on client/src/pages/SubscriptionPage.jsx
> +                className={`left-1 top-0 font-semibold cursor-text absolute transition-all
fix défaut de la logique pour garder le label en -top-4 quand il y a du texte dans le champ

2024-06-20 12:07 UTC, FranckWebPro approved these changes

2024-06-20 15:40 UTC, Yoann-Fortin requested changes

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +  font-size: 1rem;
Dead code

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +label:focus {
Dead code

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/Header.jsx
> +      document.body.classList.add("overflow-hidden");
toggle is better

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/Header.jsx
> +  const signInClasses = `
Too much code duplication

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/HeroSection.jsx
> +    <header
Wrong uses this tag

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/Navbar.jsx
> +        id="navbar"
no justify

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/Slider.jsx
> +const sportList = [
This logic must be transmitted by the parent

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/infoSection.jsx
> +    <section
no justify

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/components/registerSection.jsx
> +    <section
no justify

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +  font-size: 1rem;
Dead code

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +  transition: all ease 300ms;
You'll need to disable the animations

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +  transition: all ease 300ms;
same

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +.center {
Dead code

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +.img-shadow {
Dead code

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/index.css
> +.line-burger {
config tailwind

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/App.jsx
> +      <main>
Two main ?

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/pages/HomePage.jsx
> +      <section className="pt-24 pb-16 md:pt-32">
why ?

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/src/pages/SubscriptionPage.jsx
Separate logic from display

2024-06-20 15:40 UTC, Yoann-Fortin commented on client/tailwind.config.js
wrong names

2024-06-20 15:40 UTC, Yoann-Fortin commented on server/app/config.js
> +app.use(cors());
other line to decomment

2024-06-26 14:30 UTC, Yoann-Fortin requested changes

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/components/SignIn.jsx
> +      <figure className="hidden lg:flex justify-center">
The figure tag is generally used in conjunction with the figcaption tag.

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/components/SignIn.jsx
> +      <article className="w-96">
This article tag is used for styling, I think.

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/components/Slider.jsx
> +          <p className="flex justify-center items-center font-bold">
It's strange not to be able to click on the text but only on the image. Something to think about

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/components/Subscription.jsx
> +      <figure className="hidden lg:flex items-center justify-center">
See comment above

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/index.css
> +  outline: none;
Disabling the outline property without managing focus disables the default keyboard navigation behavior to indicate that this element has taken focus. Either leave the default behavior, or manage to signal focus

2024-06-26 14:30 UTC, Yoann-Fortin commented on client/src/pages/SubscriptionPage.jsx
> +  const handleClickProfessional = () => {
Duplicate code

2024-06-27 09:28 UTC, Yoann-Fortin requested changes

2024-06-27 09:28 UTC, Yoann-Fortin commented on client/src/components/Slider.jsx
> +          <p className="flex justify-center items-center font-bold">
A p tag cannot be inside an a tag

2024-06-27 09:28 UTC, Yoann-Fortin commented on client/src/pages/SubscriptionPage.jsx
> +  const handleClickCustomer = () => {
Code is always duplicated between handleClickCustomer and handleClickProfessional

2024-07-01 07:06 UTC, Sylvainlfe approved these changes

2024-07-01 10:06 UTC, Yoann-Fortin approved these changes

2024-07-01 10:06 UTC, merged