fix navbar and some more for main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #17
Opened 2024-06-24 13:40 UTC by sachaig

2024-06-24 14:35 UTC, FabienRollet approved these changes

2024-06-25 07:36 UTC, Yoann-Fortin requested changes

2024-06-25 07:36 UTC, Yoann-Fortin commented on client/src/components/Header.jsx
Too much duplicate code

2024-06-25 07:36 UTC, Yoann-Fortin commented on server/app/config.js
>        process.env.CLIENT_URL, // keep this one, after checking the value in `server/.env`
Do you really want to allow access to these domain names on the front line?

2024-06-25 12:44 UTC, closed without merging