Category Controller and Model
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #18
Opened 2024-06-24 15:15 UTC by FranckWebPro

2024-06-24 15:17 UTC, Sylvainlfe approved these changes

2024-06-25 07:19 UTC, KevinDavoust requested changes

2024-06-25 07:19 UTC, KevinDavoust commented on server/app/config.js
>        "http://mysite.com",
pourquoi laisser ces noms de domaine dans les cors ?

2024-06-25 07:19 UTC, KevinDavoust commented on server/app/config.js
> +// const cors = require("cors");
commentaire

2024-06-25 07:19 UTC, KevinDavoust commented on server/app/config.js
> +// app.use(cors());
commentaire

2024-06-25 15:12 UTC, Elea641 approved these changes

2024-06-25 15:15 UTC, merged