Homepage
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #3
Opened 2024-06-13 11:58 UTC by FranckWebPro

2024-06-13 12:20 UTC, sachaig commented on client/src/components/HomeSection.jsx
>            alt="a runner"
alt in french if website text = french

2024-06-13 12:21 UTC, sachaig reviewed
almost done

2024-06-13 12:26 UTC, FabienRollet requested changes

2024-06-13 12:26 UTC, FabienRollet commented on client/src/index.css
> +  --primaryLight: rgba(225, 183, 255, 0.7);
Hexa pls

2024-06-13 12:26 UTC, FabienRollet commented on client/src/index.css
> +  display: flex;
remove pls

2024-06-13 12:26 UTC, FabienRollet commented on client/src/components/HomeSection.jsx
> +          alt="a runner"
frnech plz

2024-06-13 12:31 UTC, FranckWebPro commented on client/src/index.css
> +  --primaryLight: rgba(225, 183, 255, 0.7);
Nope

2024-06-13 12:54 UTC, Sylvainlfe approved these changes

2024-06-13 13:34 UTC, Yoann-Fortin requested changes

2024-06-13 13:34 UTC, Yoann-Fortin commented on client/src/components/HeroSection.jsx
> +      <hgroup className="flex flex-col gap-2 justify-center items-center lg:items-start">
Wrong uses to hgroup

2024-06-13 13:34 UTC, Yoann-Fortin commented on client/src/App.css
To delete

2024-06-17 13:17 UTC, Elea641 requested changes

2024-06-17 13:17 UTC, Elea641 commented on client/package.json
> +    "fluid-tailwind": "^1.0.0",
Fluid-tailwind à ajouter dans les devDepencies stp

2024-06-17 13:17 UTC, Elea641 commented on client/src/components/HeroSection.jsx
> +      <section className="w-auto flex flex-col gap-2 justify-center items-center lg:items-start">
Le header doit être inclut dans la section

2024-06-17 13:17 UTC, Elea641 commented on client/src/components/registerSection.jsx
> +        alt="un coureur"
Si les alt n'apportent pas d'information plutôt préférer ""

2024-06-17 13:17 UTC, Elea641 commented on client/src/components/infoSection.jsx
> +        alt="une femme qui fait du crossfit"
Si les alt n'apportent pas d'information plutôt préférer ""

2024-06-17 13:17 UTC, Elea641 commented on client/src/index.css
>  a:visited {
code mort car déjà inclu dans ton a

2024-06-18 07:20 UTC, merged