Authant
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #36
Opened 2024-07-02 13:50 UTC by FabienRollet

2024-07-02 15:30 UTC, Sylvainlfe approved these changes

2024-07-08 06:52 UTC, Sylvainlfe approved these changes

2024-07-08 07:33 UTC, KevinDavoust requested changes

2024-07-08 07:33 UTC, KevinDavoust commented on client/src/pages/LoginPage.jsx
> +      console.info(response);
rien dans la console

2024-07-08 07:33 UTC, KevinDavoust commented on client/src/pages/RegisterPage.jsx
> +      console.info(response);
rien dans la console

2024-07-08 08:13 UTC, merged