Fix before merge dev to main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #49
Opened 2024-07-13 20:22 UTC by FranckWebPro

2024-07-13 20:33 UTC, FabienRollet approved these changes

2024-07-14 12:03 UTC, sachaig approved these changes

2024-07-14 12:21 UTC, Sylvainlfe approved these changes

2024-07-15 10:19 UTC, Yoann-Fortin requested changes

2024-07-15 10:19 UTC, Yoann-Fortin commented on client/src/components/Navbar.jsx
Remove links from buttons

2024-07-15 10:36 UTC, sachaig commented on client/src/components/Navbar.jsx
Done in PR #52 close nav when click outside

2024-07-15 12:34 UTC, Yoann-Fortin approved these changes

2024-07-15 12:34 UTC, merged