S01 page visionnage
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #6
Opened 2024-06-13 12:50 UTC by FabienRollet

2024-06-13 12:52 UTC, sachaig commented on client/src/pages/ViewingPage.jsx
> +      <section className="">
no need classname

2024-06-13 12:55 UTC, Sachaig approved these changes

2024-06-14 16:33 UTC, Yoann-Fortin requested changes

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/src/App.css
Why an empty file ?

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/src/components/HeroSection.jsx
> +      <div className="flex flex-col gap-2 justify-center items-center lg:items-start">
Why uses this div tag ?

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/src/index.css
> +a:visited {
Dead code

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/src/main.jsx
> +        path: "/Viewing",
to lowercase please

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/style.html
>        <div className="center">
Why am I rereading this page again?

2024-06-14 16:33 UTC, Yoann-Fortin commented on client/tailwind.config.js
Same

2024-06-17 13:34 UTC, Elea641 requested changes

2024-06-17 13:34 UTC, Elea641 commented on client/src/index.css
> +  --primaryLight: rgba(225, 183, 255, 0.7);
Si vous utilisez du exa ne passez pas sur du rgba

2024-06-17 13:34 UTC, sachaig approved these changes
All good

2024-06-17 14:03 UTC, merged