Footer
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #7
Opened 2024-06-13 19:42 UTC by FabienRollet

2024-06-14 08:42 UTC, FranckWebPro requested changes

2024-06-14 08:42 UTC, FranckWebPro commented on client/src/components/Footer.jsx
> +            <h3>
H3 dans le UL directement

2024-06-14 08:42 UTC, FranckWebPro commented on client/src/components/Footer.jsx
> +              <section className="pt-0 lg:px-0">
Section pas nécessaire

2024-06-14 09:34 UTC, Sylvainlfe approved these changes

2024-06-14 16:14 UTC, Yoann-Fortin commented on client/style.html
>        <div className="center">
Why this div tag ?

2024-06-17 14:33 UTC, Elea641 approved these changes

2024-06-17 14:37 UTC, merged