schema.sql, seeders and cors installation
WildCodeSchool-2024-02/JS-bdx-0224-P3-Origin_digital pull request #9
Opened 2024-06-18 07:35 UTC by FranckWebPro

2024-06-18 07:48 UTC, FabienRollet approved these changes

2024-06-18 08:02 UTC, Elea641 requested changes

2024-06-18 08:02 UTC, Elea641 commented on server/database/fixtures/UserSeeder.js
> +  async run() {
le async est nécessaire ici ?

2024-06-18 08:02 UTC, Elea641 commented on server/database/fixtures/VideoSeeder.js
> +  async run() {
Idem

2024-06-18 08:02 UTC, Elea641 commented on server/database/fixtures/Video_TagSeeder.js
> +  async run() {
idem

2024-06-18 08:56 UTC, Sylvainlfe approved these changes

2024-06-19 07:17 UTC, Elea641 approved these changes

2024-06-19 07:17 UTC, merged